# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "./"
  command = "yarn export"
  publish = "public"

[dev]
  command = "yarn dev"

